import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Builds the showcase site into website/dist: every scenario document is
// generated by the actual CLI against the scenario's real MikroORM config, so
// the site always shows what the current code produces — nothing hand-written.

const websiteDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(websiteDir, '..');
const cliPath = path.join(repoRoot, 'dist', 'cli.js');
const outDir = path.join(websiteDir, 'dist');

const SCENARIOS = [
  {
    id: 'full-tour',
    title: 'Full tour',
    blurb:
      'The complete examples/ schema — every relation kind, inheritance, embeddables, ' +
      '@namespace groups, and column markers in one document.',
    dir: path.join(repoRoot, 'examples'),
    entitiesDir: path.join(repoRoot, 'examples', 'entities'),
    docTitle: 'Example Schema',
    docDescription:
      'Generated from the entities in examples/entities - a tour of every feature mikro-orm-markdown can render.',
  },
  {
    id: 'relations-namespaces',
    title: 'Relations & namespaces',
    blurb:
      'Three small entities across two @namespace groups show how relations render in the ERD ' +
      'and how groups shape the document.',
    dir: path.join(websiteDir, 'scenarios', 'relations-namespaces'),
    entitiesDir: path.join(websiteDir, 'scenarios', 'relations-namespaces', 'entities'),
    docTitle: 'Org & Delivery',
    docDescription: 'Relations across two namespace groups.',
  },
  {
    id: 'hidden-entityschema',
    title: '@hidden & EntitySchema',
    blurb:
      '@hidden removes an entity (and its relations) from every output; an EntitySchema-defined ' +
      'entity renders from metadata right next to decorator entities.',
    dir: path.join(websiteDir, 'scenarios', 'hidden-entityschema'),
    entitiesDir: path.join(websiteDir, 'scenarios', 'hidden-entityschema', 'entities'),
    docTitle: 'Visibility & EntitySchema',
    docDescription: 'What @hidden removes, and how schema-defined entities render.',
  },
];

if (!existsSync(cliPath)) {
  throw new Error('dist/cli.js not found - run `npm run build` before building the website.');
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(path.join(outDir, 'scenarios'), { recursive: true });
cpSync(path.join(websiteDir, 'public'), outDir, { recursive: true });

const index = [];
for (const scenario of SCENARIOS) {
  process.stdout.write(`[website] generating scenario: ${scenario.id}\n`);
  const mdPath = path.join(outDir, 'scenarios', `${scenario.id}.md`);
  execFileSync(
    'node',
    [cliPath, '-c', 'mikro-orm.config.ts', '-o', mdPath, '-t', scenario.docTitle, '-d', scenario.docDescription],
    { cwd: scenario.dir, stdio: 'inherit' }
  );

  const files = readdirSync(scenario.entitiesDir)
    .filter((name) => name.endsWith('.ts'))
    .sort()
    .map((name) => ({ name, code: readFileSync(path.join(scenario.entitiesDir, name), 'utf-8') }));

  const payload = {
    id: scenario.id,
    title: scenario.title,
    blurb: scenario.blurb,
    files,
    markdown: readFileSync(mdPath, 'utf-8'),
  };
  writeFileSync(path.join(outDir, 'scenarios', `${scenario.id}.json`), JSON.stringify(payload));
  rmSync(mdPath);

  index.push({ id: scenario.id, title: scenario.title });
}

writeFileSync(path.join(outDir, 'scenarios', 'index.json'), JSON.stringify(index));
process.stdout.write(`[website] built ${SCENARIOS.length} scenarios into ${outDir}\n`);
